resolver: lts-15.11

ghc-options: {"$locals": -fwrite-ide-info}

extra-deps:
  # --- Transitive Pact Dependencies --- #
  - direct-sqlite-2.3.26
  - ed25519-donna-0.1.1
  - prettyprinter-1.6.0
  - sbv-8.6
  - github: kadena-io/thyme
    commit: 6ee9fcb026ebdb49b810802a981d166680d867c9

  # --- Custom Pins --- #
  - github: kadena-io/pact
    commit: a7ec56659745792cf6e579e45209045a6ee91d66
  - github: kadena-io/signing-api
    commit: bba10d2d561d823774a78af706d72d5fca465766
    subdirs: [kadena-signing-api]
