resolver: lts-14.22

ghc-options: {"$locals": -ddump-to-file -ddump-hi}

extra-deps:
  # --- Transitive Pact Dependencies --- #
  - ed25519-donna-0.1.1
  - sbv-8.2
  - trifecta-2.1
  - github: kadena-io/thyme
    commit: 6ee9fcb026ebdb49b810802a981d166680d867c9

  # --- Custom Pins --- #
  - github: kadena-io/pact
    commit: 8985ec8d0231306b1456744056d30767ae236e28
  - github: kadena-io/signing-api
    commit: 68075be0ba5a1c361ca8416ae993cff42374fdd3
    subdirs: [kadena-signing-api]
